server:
  port: 9000

github:
  client_id: e7341630e86488e64e11
  client_secret: 3d87ba58ec8201d8672358bcfa44dbf17f2fa48d
  redirect_uri: http://localhost:9000/github/callback

spring:
  datasource:
    url: jdbc:mysql:///imust_bbs
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
  type-aliases-package: top.codingdong.imustbbs.mapper
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  # 分页合理化
  reasonable: true

